"""Initial schema

Revision ID: b000f2425625
Revises: 
Create Date: 2026-09-14 16:46:31.819267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b000f2425625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('customer_type', sa.Enum('Individual', 'Business', 'Government', 'NGO', name='customer_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email', name='uk_customer_email')
    )
    op.create_table('equipment_type',
    sa.Column('equipment_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('Solar Panel', 'Battery', 'Inverter', 'Charge Controller', 'Mounting', 'Accessory', name='equipment_category_enum'), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_number', sa.String(length=50), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_warranty_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('default_warranty_months > 0', name='chk_equipment_type_warranty_months'),
    sa.CheckConstraint('unit_price > 0', name='chk_equipment_type_unit_price'),
    sa.PrimaryKeyConstraint('equipment_type_id'),
    sa.UniqueConstraint('model_number', name='uk_equipment_type_model_number')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('Administrator', 'Sales Rep', 'Operations Manager', 'Technician', 'Warehouse Clerk', 'Customer Service', 'Finance Officer', 'Auditor', name='staff_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email', name='uk_staff_email'),
    sa.UniqueConstraint('username', name='uk_staff_username')
    )
    op.create_table('technician',
    sa.Column('technician_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialisation', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('technician_id'),
    sa.UniqueConstraint('email', name='uk_technician_email')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], name='fk_audit_staff_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('site',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('site_type', sa.Enum('Household', 'School', 'Farm', 'Business', 'Government', name='site_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='fk_site_customer_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('equipment',
    sa.Column('equipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Available', 'Reserved', 'Installed', 'Faulty', 'Decommissioned', name='equipment_status_enum'), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.equipment_type_id'], name='fk_equipment_equipment_type_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], name='fk_equipment_site_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('equipment_id'),
    sa.UniqueConstraint('serial_number', name='uk_equipment_serial_number')
    )
    op.create_table('installation',
    sa.Column('installation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'In Progress', 'Completed', 'Cancelled', name='installation_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], name='fk_installation_created_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], name='fk_installation_site_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_table('installation_assignment',
    sa.Column('install_assign_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.Column('role_in_team', sa.Enum('Lead', 'Assistant', name='role_in_team_enum'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.installation_id'], name='fk_installation_assignment_installation_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.technician_id'], name='fk_installation_assignment_technician_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('install_assign_id'),
    sa.UniqueConstraint('installation_id', 'technician_id', name='uk_installation_assignment')
    )
    op.create_table('installation_detail',
    sa.Column('install_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_at_install', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='chk_installation_detail_quantity'),
    sa.CheckConstraint('unit_price_at_install > 0', name='chk_installation_detail_price'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name='fk_installation_detail_equipment_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.installation_id'], name='fk_installation_detail_installation_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('install_detail_id'),
    sa.UniqueConstraint('equipment_id', name='uk_installation_detail_equipment_id'),
    sa.UniqueConstraint('installation_id', 'equipment_id', name='uk_installation_detail_install_equip')
    )
    op.create_table('service_request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('date_raised', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='service_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Resolved', 'Closed', name='service_status_enum'), nullable=False),
    sa.Column('date_resolved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name='fk_service_request_equipment_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['staff.staff_id'], name='fk_service_request_reported_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], name='fk_service_request_site_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('warranty',
    sa.Column('warranty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('warranty_type', sa.Enum('Manufacturer', 'Extended', 'SolarGrid', name='warranty_type_enum'), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Expired', 'Claimed', 'Voided', name='warranty_status_enum'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='chk_warranty_dates'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name='fk_warranty_equipment_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('warranty_id')
    )
    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Issued', 'Partially Paid', 'Paid', 'Overdue', 'Cancelled', name='invoice_status_enum'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_paid >= 0', name='chk_invoice_amount_paid'),
    sa.CheckConstraint('due_date >= date_issued', name='chk_invoice_due_date'),
    sa.CheckConstraint('total_amount > 0', name='chk_invoice_total_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['staff.staff_id'], name='fk_invoice_created_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name='fk_invoice_customer_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.installation_id'], name='fk_invoice_installation_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['service_request.request_id'], name='fk_invoice_request_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number', name='uk_invoice_number')
    )
    op.create_table('maintenance_record',
    sa.Column('maintenance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('hours_worked > 0', name='chk_maintenance_hours_worked'),
    sa.ForeignKeyConstraint(['request_id'], ['service_request.request_id'], name='fk_maintenance_request_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.technician_id'], name='fk_maintenance_technician_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('service_assignment',
    sa.Column('service_assign_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_request.request_id'], name='fk_service_assignment_request_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.technician_id'], name='fk_service_assignment_technician_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('service_assign_id'),
    sa.UniqueConstraint('request_id', 'technician_id', name='uk_service_assignment')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('Cash', 'EFT', 'Credit Card', 'Debit Order', 'Cheque', name='payment_method_enum'), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Confirmed', 'Reversed', name='payment_status_enum'), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_payment_amount'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_id'], name='fk_payment_invoice_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['staff.staff_id'], name='fk_payment_recorded_by', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('service_assignment')
    op.drop_table('maintenance_record')
    op.drop_table('invoice')
    op.drop_table('warranty')
    op.drop_table('service_request')
    op.drop_table('installation_detail')
    op.drop_table('installation_assignment')
    op.drop_table('installation')
    op.drop_table('equipment')
    op.drop_table('site')
    op.drop_table('audit_log')
    op.drop_table('technician')
    op.drop_table('staff')
    op.drop_table('equipment_type')
    op.drop_table('customer')
    # ### end Alembic commands ###
